### ISSUE TITLE
Actions of initial state are not executed

### ISSUE THREAD

**Issue by snaewe** [stateless4j/stateless4j#30]
Consider the following test case (when copied into StateMachnineTests.java) :

``` java
    @Test
    public void ActionOfInitialStateAreExecuted() {
        StateMachineConfig<State, Trigger> config = new StateMachineConfig<>();

        fired = false;

        config.configure(State.B)
                .onEntry(new Action() {

                    @Override
                    public void doIt() {
                        setFired();
                    }
                });

        StateMachine<State, Trigger> sm = new StateMachine<>(State.B, config);

        assertTrue(fired);
    }
```

Shouldn't this test pass ?

**Comment by EasonPai** [comment]
I had the same question and my problem is answered as well.

But I'm feeling UML spec seems has a much unique design than other State Machines. 
So far State Machines I tried don't have such design, IMHO it would be good to have an official option to switch between them, otherwise most users will need to do some workaround on this. Thanks!

**Comment by fabienrenaud** [comment]
I actually ran into the same problem the very first time i used stateless4j ;)
The workaround i used is to have an extra state A that would be the initial one and immediately fire its one transition to put the state machine right away on some other state B (that state B being your current initial state).
Pros: 1) it works; 2) no changes to stateless4j; 3) it is as close as possible to the UML spec
Cons: 1) extra transition to fire manually; 2) more code to write

Another solution would be to fire the entry actions of the initial state. That would require to have some configuration for the state machine executor/runner (the entity that fires the transitions) to manually turn on this feature (for backward compatibility sake).

**Comment by fabienrenaud** [comment]
Implemented: https://github.com/oxo42/stateless4j/compare/issue30?expand=1

**Comment by EasonPai** [comment]
I am back to here because the ignored of initial state is really pain in the ass.
Thanks for this great patch! Now I need to check how to use your patch, thanks again!

**Comment by ezaquarii** [comment]
Initial state actions are triggered in constructor, causing side effects on construction.
This is a no-go in situations where object life cycle is complex, suchs as `Android` components.
