### ISSUE TITLE
Multi-threaded support

### ISSUE THREAD

**Issue by samskiter** [stateless4j/stateless4j#35]
This would be possible if we wrap the existing state machine with a list of events and execute all the state machine stuff on one dedicated thread.

We'd need some 'state' about whether the StateMachine is currently busy too. If it is busy place the action on a queue. as the state machine becomes not busy, fire each event passed.

One big advantage of this is being able to fire an event from a handler - sometimes my events are based on the result of a long running action - I keep myself in a 'processing' state and when done, call a state machine trigger to leave the 'processing' state. Rather than firing this work off on a new thread, it's nice to just run it all in the entry handler then fire a new event to move on.

**Comment by samskiter** [comment]
> stuff

**Comment by Ktar5** [comment]
We're open to pull requests if you'd like to implement this
