### ISSUE TITLE
Can we use stateless4j with REST based micro service.

### ISSUE THREAD

**Issue by prabhabisht** [stateless4j/stateless4j#57]
Hi Team,
My requirement is to use state machine lib with a rest micro service,
* Need to initialize state machine with a particular state with each rest call.
* Need to configure the separate state machine on the basis of group of states.
* The event will come from some external service, we need to response back  after changing the state and perform some action.
 Can we leverage this library .

**Comment by yitdev** [comment]
I am trying to use staless4j with a rest micro service too,  if you have some suggestions? I have tried spring-statemachine, but it seems not suitable for micro service.

**Comment by TimGuan** [comment]
I am trying to use staless4j with a rest micro service too,  if you have some suggestions? I have tried spring-statemachine, but it seems not suitable for micro service.
