### ISSUE TITLE
Update Java Minimum Version to JDK8

### ISSUE THREAD

**Issue by martinei** [stateless4j/stateless4j#65]
Stateless4J introduces a number of (Functional) Interfaces that are present  in a similair form in the jdk since java 8  (Action1 ->  Consumer,  Action2 -> BiConsumer, Func -> Supplier, Func2 -> Function, Func3 -> BiFunction, FuncBoolean -> BooleanSupplier).

What do you think about updating to a more recent java, removing the duplicates and renaming some of the other interfaces to match the JDK  Naming (e.g. Func4 -> TriFunction,  Action3 ->  TriConsumer)? Using the familiar names would make it easier for the reader.

**Comment by Ktar5** [comment]
I'm not entirely sure about this, though I have thought about it. I'll leave this issue open for a while and see if there is any other expressed interest in this. If so, it'll happen, if not-- it's a non-issue.

**Comment by binkley** [comment]
I found this project through a GitHub issue in JUnit (https://github.com/junit-team/junit5/issues/48#issuecomment-161938851).

Given that Java 11 is the LTS version, and Java 13 is heading our way ... what is the maintenance status of this project?  :)

**Comment by ezaquarii** [comment]
@martinei Since I took the maintainership, I'm open to modernization proposals. If you are interested in helping out, let me know.

**Comment by ezaquarii** [comment]
@binkley This project has been almost abandoned, but since I'm using it in other projects, I took ownership of it now. I'll try to gradually make it in better shape. Let me know if you are interested in helping out.

**Comment by ezaquarii** [comment]
There are 2 reasons why we'd like to keep old interfaces:

1. existing users will be forced to migrate their solutions
2. `Android` runtime pre API-24 still does not support many JDK8 classes and this is substantial developer demographic I'd like to support 

I'll bump language to Java8 to enable use of language features, but I do not plan to refactor APIs in the near future.
