### ISSUE TITLE
Action2 parameters are flipped

### ISSUE THREAD

**Issue by sudeshbainsla** [stateless4j/stateless4j#69]
`public <TArg0> StateConfiguration<S, T> onEntryFrom(TriggerWithParameters1<TArg0, S, T> trigger, final Action2<**TArg0, Transition<S, T>**> entryAction, Class<TArg0> classe0) {`

But while firing, the entry action execution flips the parameters-
```
void executeEntryActions(Transition<S, T> transition, Object[] entryArgs) {
...
while(var3.hasNext()) {
            Action2<**Transition<S, T>, Object[]**> action = (Action2)var3.next();
            action.doIt(transition, entryArgs);
        }
```

**Comment by Ktar5** [comment]
I'll look into this during the upcoming weekend. Thanks for the report.

**Comment by juddgaddie** [comment]
Is this something you are supporting?

**Comment by ezaquarii** [comment]
Quoted code snippet does not exist in library source code.
